[package]
name = "norr_kernel"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
noto-sans-mono-bitmap = { version = "0.3.2", default-features = false, features = [
    "regular",
    "size_20",
    "unicode-basic-latin",
] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
