name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Build x86_64 UEFI
        run: cargo build --target x86_64-unknown-uefi

      - name: Build aarch64 UEFI
        run: cargo build --target aarch64-unknown-uefi
